name: TinyHeelerAI
on:
  push:
    branches:
      - main
jobs:
  staging-deploy:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy docker
        id: deploy_docker
        uses: JimCronqvist/action-ssh@master
        with:
          hosts: ubuntu@171.244.52.37
          privateKey: ${{ secrets.PRIVATE_SSH_KEY }}
          command: |
            cd /opt/huy-dev/TinyHealerAI
            git pull
            sudo docker-compose up -d --build